version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: request
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: