server:
  port: 8090
spring:
  application:
    name: "request-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
logging:
  level:
    co.com.pragma: "trace"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
      base-path: /request/actuator
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
services:
  auth:
    url: "http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "request"
    schema: "public"
    username: "admin"
    password: "admin"
    ssl: false
jwt:
  secret: ${JWT_SECRET}
entrypoint:
  sqs:
    region: ${AWS_REGION}
    queueUrl: ${AWS_SQS_RESPONSE_ENDEUDAMIENTO}
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
adapter:
  sqs:
    region: ${AWS_REGION}
    queues:
      indebtedness: ${AWS_SQS_ENDEUDAMIENTO}
      notifications: ${AWS_SQS_NOTIFICACIONES}
      reporting: ${AWS_SQS_REPORTES}

queue:
  names:
    indebtedness: indebtedness
    notifications: notifications
    reporting: reporting

