server:
  port: 8090
spring:
  application:
    name: "request-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
logging:
  level:
    co.com.pragma: "trace"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
services:
  auth:
    url: "http://localhost:8080"
adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "request"
    schema: "public"
    username: "admin"
    password: "admin"
jwt:
  secret: "rXm5xuejgjmoMoOaaP5G5EUl6Wl+nZxjHLMx2n8IPHE="
cloud:
  aws:
    region:
      static: "${AWS_REGION}"
      auto: false
    credentials:
      access-key: "${AWS_ACCESS_KEY_ID}"
      secret-key: "${AWS_SECRET_ACCESS_KEY}"
    end-point:
      uri: "${AWS_SQS_ENDPOINT}"
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "http://localhost:4566/000000000000/sample"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
