server:
  port: 8080
spring:
  application:
    name: "request-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    requests: "/api/v1/requests"

adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "request"
    schema: "public"
    username: "admin"
    password: "admin"