server:
  port: 8080

adapters:
  r2dbc:
    host: ${ADAPTERS_R2DBC_HOST}
    port: ${ADAPTERS_R2DBC_PORT}
    database: ${ADAPTERS_R2DBC_DB}
    username: ${ADAPTERS_R2DBC_USER}
    password: ${ADAPTERS_R2DBC_PASS}

services:
  auth:
    url: ${SERVICES_AUTH_URL}

app:
  timezone: ${TIME_ZONE}